routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/home', function () {
    return view('pages.home');
});

Route::get('/about', function () {
    return view('pages.about');
});

Route::get('/products', function () {
    return view('pages.products');
});

Route::get('/productForm', function () {
    return view('pages.productForm');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Auth::routes();

//CRUD URLs
Route::Resources([
	'users'=>'UsersController',
	'products'=>'ProductController',
	'product'=>'ProductController'
]);

resources/views/pages/about.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">About Us</div>

                <div class="card-body">
                  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/home.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Home</div>

                <div class="card-body">
                  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/notAuth.blade.php
@extends('layout.default')
@section('content')
@if(count($errors) > 0)
<div class="alert alert-danger">
Inserting validation error<br><br>
  <ul>
    @foreach($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
@if (\Session::has('success'))
    <div class="alert alert-success">
        <ul>
            <li>{!! \Session::get('success') !!}</li>
        </ul>
    </div>
@endif
    <h1 style="text-align:center"> ERROR: Not Authorized. </h1>

@endsection

resources/views/pages/product.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Product</div>
                
                <div class="card-body">
                    <form method="post" action="{{route('products.update', $product->id)}}" enctype="multipart/form-data"> {!! method_field('put') !!} {{ csrf_field() }}
                        @csrf
                        <div class="form-group row">
                            <label for="nameProduct" class="col-md-4 col-form-label text-md-right">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nameProduct" value="{{$product->name}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="descriptionProduct" class="col-md-4 col-form-label text-md-right">Description</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="descriptionProduct" value="{{$product->description}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="priceProduct" class="col-md-4 col-form-label text-md-right">Price</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="priceProduct" value="{{$product->price}}" required>
                            </div>
                        </div>

                        <div id="Buttons">
                            <button type="reset" class="btn btn-outline-info">Reset</button>
                            <button type="submit" class="btn btn-warning" id="black">Edit</button>
                            <a href="{{URL::previous()}}" class="btn btn-outline-dark">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/productDetail.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Product</div>
                
                <div class="card-body">
                    <form method="post" action="{{route('products.update', $product->id)}}" enctype="multipart/form-data"> {!! method_field('put') !!} {{ csrf_field() }}
                        @csrf
                        <div class="form-group row">
                            <label for="nameProduct" class="col-md-4 col-form-label text-md-right">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nameProduct" value="{{$product->name}}" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="descriptionProduct" class="col-md-4 col-form-label text-md-right">Description</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="descriptionProduct" value="{{$product->description}}" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="priceProduct" class="col-md-4 col-form-label text-md-right">Price</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="priceProduct" value="{{$product->price}}" required readonly>
                            </div>
                        </div>

                        <div id="Buttons">
                            <button type="submit" class="btn btn-warning" id="black">Add to Cart</button>
                            <a href="{{URL::previous()}}" class="btn btn-outline-dark">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/productForm.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Product') }}</div>
                
                <div class="card-body">
                    <form method="POST" action="{{route('products.store')}}" enctype="multipart/form-data">
                        @csrf
                        
                        <div class="form-group row">
                            <label for="nameProduct" class="col-md-4 col-form-label text-md-right">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nameProduct" placeholder="Name" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="descriptionProduct" class="col-md-4 col-form-label text-md-right">Description</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="descriptionProduct" placeholder="Description" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="priceProduct" class="col-md-4 col-form-label text-md-right">Price</label>
                            <div class="col-md-6">
                                <input type="number" class="form-control" name="priceProduct" placeholder="Price" required>
                            </div>
                        </div>

                        <div id="Buttons">
                            <button type="reset" class="btn btn-outline-info">Reset</button>
                            <button type="submit" class="btn btn-warning" id="black">Create</button>
                            <a href="{{URL::previous()}}" class="btn btn-outline-dark">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/products.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
			@if(Auth::check() && Auth::user()->role_id == 1)
				<a href="{{route('products.create')}}" class="btn btn-primary">Add Product</a> 
			@endif
			@foreach($products as $product)
				<div class="card">
					<div class="card-header">
						<b class="float-sm-left">{{ $product->name }}</b>
						@if(Auth::check() && Auth::user()->role_id == 1)
							<a href="/products/{{ $product->id }}" class="btn btn-primary float-sm-right">Edit Product</a> 
							<form id="delete-product" action="{{ route('product.destroy', $product->id) }}" method="POST">
							{{ csrf_field() }}
							@method('DELETE')
								<button class="btn btn-danger float-sm-right" type="submit" onclick="return confirm('Are you sure?')">Delete Product</button>
							</form>
						@endif
					</div>
					<div class="card-body">
						<ul>
							<p>Description: {{ $product->description }}</p>
							<p>Price: ${{ $product->price }}</p>
							<a href="{{route('products.edit', $product->id)}}" class="btn btn-primary float-sm-right">See Details</a> 
						</ul>
					</div>
				</div>
			@endforeach
        </div>
    </div>
</div>
@endsection

resources/views/pages/profile.blade.php
@extends('layout.default')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Profile</div>
                
                <div class="card-body">
                    <form method="post" action="{{route('users.update', $user->id)}}" enctype="multipart/form-data"> {!! method_field('put') !!} {{ csrf_field() }}
                        @csrf
                        <div class="form-group row">
                            <label for="emailUser" class="col-md-4 col-form-label text-md-right">E-mail</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="emailUser" value="{{$user->email}}" readonly="true" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nameUser" class="col-md-4 col-form-label text-md-right">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nameUser" value="{{$user->name}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="zipCodeUser" class="col-md-4 col-form-label text-md-right">Zip Code</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="zipCodeUser" value="{{$user->zip_code}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="addressUser" class="col-md-4 col-form-label text-md-right">Address</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="addressUser" value="{{$user->address}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phoneNumberUser" class="col-md-4 col-form-label text-md-right">Phone Number</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="phoneNumberUser" value="{{$user->phone_number}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="img" class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>
                            <div class="col-md-6">
                                <img class="img-rounded corners" width="60px" src="{{ asset('images/user/'.$user->image) }}" alt="">
                            </div>
                            
                        </div>
                        <div class="form-group row">
                            <label for="userImage" class="col-md-4 col-form-label text-md-right"></label>
                            <div class="col-md-6">
                                <input type="file" class="form-control-file" name="userImage" accept="image/*">
                            </div>
                        </div>

                        <div id="Buttons">
                            <button type="reset" class="btn btn-outline-info">Reset</button>
                            <button type="submit" class="btn btn-warning" id="black">Edit</button>
                            <a href="{{URL::previous()}}" class="btn btn-outline-dark">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection